### ISSUE TITLE
Por qué hace falta aplicar la función id?

### ISSUE THREAD

**Issue by natoszme** [alexmclm/pdep2020TP#3]
https://github.com/alexmclm/pdep2020TP/blob/ec3074b3dca8ac66327168fbb0c6da88b56e4c20/tp1.hs#L55

**Comment by alexmclm** [comment]
debido a que interprete que tiene que tener ciertas tacticas para que haga "lo otro", en este caso restar la propiedad de su dinero y sumarle la adquisicion de la propiedad
y como usando guardas no puedo dejar la condicion para todo el resto, le puse el otherwise, y como no tiene condicion, mejor que devuelva la id de la persona en si jaajaj
si bien esto no lo dice explicitamente el tp, lo interprete asi
esta mal¿

**Comment by natoszme** [comment]
Está ok agregar el otherwise, lo que no entiendo es por qué devolver `id unaPersona` en vez de   `unaPersona`
